# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


def pods
    pod 'Alamofire', '4.5.0'
    pod 'PromiseKit', '~> 4.0'
end

def testOnly
    pod 'Quick'
    pod 'Nimble'
    pod 'OHHTTPStubs/Swift'
end


target 'PlayolaCoreIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pods()

  target 'PlayolaCoreIOSTests' do
    inherit! :search_paths
    testOnly()
  end

end

target 'PlayolaCoreOSX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pods()

  target 'PlayolaCoreOSXTests' do
    inherit! :search_paths
    testOnly()
  end
  
end
