# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlayolaCoreIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlayolaCoreIOS

  target 'PlayolaCoreIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PlayolaCoreOSX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlayolaCoreOSX

  target 'PlayolaCoreOSXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
